### ISSUE TITLE
Simulation Problem with sub-circuits

### ISSUE THREAD

**Issue by davidhutchens** [logisim-evolution/logisim-evolution#1160]
Here is a sample circuit that when loaded in the current develop branch, shows the output of the subcircuit as undefined, but if you look in the subcircuit, the output is zero. It works correctly in earlier builds.

[SimulationProblem1.circ.zip](https://github.com/logisim-evolution/logisim-evolution/files/7255189/SimulationProblem1.circ.zip)

Here is a simpler example with just one bit in a subcircuit that just passes it to the output.

[simpleSubcircuit.circ.zip](https://github.com/logisim-evolution/logisim-evolution/files/7266979/simpleSubcircuit.circ.zip)

In this simple example, loading it shows the output of main (received from the subcircuit) as U. It should be 0. Changing the input to the subcircuit does not change that. However, if you select the Simulate panel and expand main to see and open the subcircuit you'll see it is outputting its input. Now, strangely, if you go back to main, it will put the previous thing that was output on its output. Switch the input and repeat opening the subcircuit and go back to main. It then has the opposite value. So it isn't the current outputted value but the previous one you looked at.... Very strange.

**Comment by MarcinOrlowski** [comment]
>  It works correctly in earlier builds.

David, will you be able to narrow the commit that broke it?

**Comment by davidhutchens** [comment]
Likely, yes. I had other things to do for a while. I'll look at it later.

**Comment by MarcinOrlowski** [comment]
Great, thanks. You are aware of bisection approach that can save you some time and effort there?

**Comment by davidhutchens** [comment]
Aware of a bisection approach? Yeah. I may have been teaching binary searches before you were born :-). Anyway, commit da88fe975531d235c0f09362c3c071a01a545148 is good. 19f3ed03998659f7c2e1c6482a991c9f46320ab1 doesn't work. d9cd0fcf939f223686f8e11a005fa2c028aae0be is in the middle of them, but doesn't compile.

**Comment by MarcinOrlowski** [comment]
Heh, that's possible :) But I thought compilation issue is one thing (which is now fixed) and simulation problems is another, no? As #1159 is merged project should compile just fine (unless I miss something?) but you said `d9cd0fc is in the middle of them, but doesn't compile.` however the `null` bug was introduced in `a3710b38683eb3dcf67d867223c0450820202462`:

```bash
$ git show a3710b3868 --stat
commit a3710b38683eb3dcf67d867223c0450820202462
Date:   Wed Sep 29 11:32:33 2021 +0200
```

which is **later** commit than `d9cd0fc`:

```bash
$ git show d9cd0fc --stat
commit d9cd0fcf939f223686f8e11a005fa2c028aae0be
Date:   Tue Sep 28 14:45:40 2021 +0200
```

What do I misunderstand?

**Comment by davidhutchens** [comment]
I was testing in Java 16, so the null bug was not the cause of the failure in d9cd0fcf939f223686f8e11a005fa2c028aae0be. It fails with:
`logisim-evolution/src/main/java/com/cburch/logisim/fpga/hdlgenerator/InlinedHdlGeneratorFactory.java:19: error: InlinedHdlGeneratorFactory is not abstract and does not override abstract method generateAllHDLDescriptions(Set<String>,String,List<String>) in HdlGeneratorFactory
public class InlinedHdlGeneratorFactory implements HdlGeneratorFactory {
       ^
`

**Comment by MarcinOrlowski** [comment]
Hm, [but for me it does](https://github.com/logisim-evolution/logisim-evolution/blob/develop/src/main/java/com/cburch/logisim/fpga/hdlgenerator/InlinedHdlGeneratorFactory.java#L22)? How recent is your develop?l

**Comment by davidhutchens** [comment]
I'm confused by your comment. The three commits I listed above were in a row in the history. The one "in the middle" did  not compile. The compile problems were fixed in the following commit (third of the series), but that one fails to run properly. The bug for this issue was introduced in either d9cd0fcf939f223686f8e11a005fa2c028aae0be or 19f3ed03998659f7c2e1c6482a991c9f46320ab1.

My develop branch was up-to-date as of yesterday. The only commit with the failure to compile because of the override issues is d9cd0fcf939f223686f8e11a005fa2c028aae0be. My current HEAD of develop compiles (well, in Java 16).

**Comment by BFH-ktt1** [comment]
@davidhutchens and @MarcinOrlowski : What is the status of this investigation?

**Comment by davidhutchens** [comment]
@BFH-ktt1 and @MarcinOrlowski : I have tried to find the cause by examining the commits that introduced it. I have not yet been successful. I am not very familiar with the simulation engine.

But I can more reliably see the problem. I added a very simple example to the initial comment above and attempted to describe what I see. Can either of you reproduce that, or at least see strange behavior? It still occurs in today's develop branch.

I view this as a critical bug since I believe it will cause failures on any .circ file that contains sub-circuits. Please do not release 3.7.0 until this is resolved.

**Comment by MarcinOrlowski** [comment]
@davidhutchens which commit is the one that makes LSe expose this issue?

**Comment by MarcinOrlowski** [comment]
> The bug for this issue was introduced in either d9cd0fc or 19f3ed0.

Both are mine. Lemme see...

**Comment by MarcinOrlowski** [comment]
I fixed compilation issues for d9cd0fcf939f223686f8e11a005fa2c028aae0be and it exposes the issue so whatever causing this was introduced here.

**Comment by BFH-ktt1** [comment]
@davidhutchens , @MarcinOrlowski : Found it, it was in [d9cd0fc](https://github.com/logisim-evolution/logisim-evolution/commit/d9cd0fcf939f223686f8e11a005fa2c028aae0be) in ```CircuitState.java```:
![Screenshot from 2021-10-01 17-45-56](https://user-images.githubusercontent.com/13875618/135650173-c3941626-d5ce-482b-b6c6-22f7f98a52dc.png)

Made a PR
